from domain.data_model import Cocktail, Dose, Method, Family, Liquid, CustomCategory


cocktails = [
    Cocktail(
        name="Alaska",
        doses=[Dose(Liquid.GIN, 1.5), Dose(Liquid.CHARTREUSE, 0.5)],
        method=Method.STIR,
        family=Family.DUOS_TRIOS,
    ),
    Cocktail(
        name="Alexander",
        doses=[Dose(Liquid.GIN, 2), Dose(Liquid.CREME_DE_CACAO, 1)],
        addons=["1 ounce cream"],
        method=Method.SHAKE,
        family=Family.DUOS_TRIOS,
    ),
    Cocktail(
        name="Almost blow my skull off",
        doses=[
            Dose(Liquid.ANCHO_VERDE, 0.25),
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.JAGERMEISTER, 0.5),
        ],
        method=Method.STIR,
        family=Family.ORPHANS,
        preparation_recommendation="Use Cognac specifically for the Brandy",
    ),
    Cocktail(
        name="Amaro Crusta",
        doses=[
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.LIME_JUICE, 0.5),
            Dose(Liquid.AMARO, 2),
        ],
        addons=["1 spoon orange marmalade", "Orange twist"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="I simplified a lot. Actual recipe with a mix of Amaros "
        "(Montenegro, Picon, Rabarbaro)."
        "Dry shake marmalade and citrus juice, then add ice and shake the rest",
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Americano",
        doses=[Dose(Liquid.CAMPARI, 1.5), Dose(Liquid.SWEET_VERMOUTH, 1.5)],
        addons=["2 ounces club Soda", "1 orange twist"],
        method=Method.BUILD,
        family=Family.HIGHBALLS,
        custom_category=CustomCategory.CLASSIC,
    ),
    Cocktail(
        name="Am I Blue",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.MARASCHINO, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 0),
            Dose(Liquid.CHAMPAGNE, None),
        ],
        addons=["1 flamed orange twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        custom_category=CustomCategory.WANT_TO_TRY,
        preparation_recommendation="Use Blue Label Johnny Walker Scotch",
    ),
    Cocktail(
        name="Angel's Share",
        doses=[
            Dose(Liquid.CHARTREUSE, 1),
            Dose(Liquid.BRANDY, 1.25),
            Dose(Liquid.WALNUT_LIQUEUR, 1.25),
            Dose(Liquid.PORTO, 0.5),
        ],
        method=Method.STIR,
        family=Family.ORPHANS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Aperol Spritz",
        doses=[Dose(Liquid.APEROL, 2), Dose(Liquid.PROSECCO, 3)],
        addons=["1 Splash Club soda", "1 Orange Wheel"],
        method=Method.BUILD,
        family=Family.ORPHANS,
        custom_category=CustomCategory.CLASSIC,
    ),
    Cocktail(
        name="Atom Limo",
        doses=[
            Dose(Liquid.WHISKEY, 1),
            Dose(Liquid.SHERRY, 1),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GINGER_ALE, None),
        ],
        addons=[
            "1 ounce apple juice",
            "Fresh Ginger",
            "1 mint sprig",
            "1 apple slice",
            "1 cherry",
        ],
        method=Method.BUILD,
        family=Family.ORPHANS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Autumn Winds",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.BENEDICTINE, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 1),
        ],
        addons=["0.5oz homemade butter sage liqueur (cf book)", "1 sage leaf"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
    ),
    Cocktail(
        name="Aviation Cocktail",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.CREME_DE_VIOLETTE, 0.5),
            Dose(Liquid.MARASCHINO, 0.25),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Aztec's Mark",
        doses=[
            Dose(Liquid.WHISKEY, 1.25),
            Dose(Liquid.BENEDICTINE, 0.25),
            Dose(Liquid.CREME_DE_CACAO, 0.5),
        ],
        addons=["2 drops Tabasco", "1 orange twist"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="Use Maker's Mark Bourbon",
    ),
    Cocktail(
        name="Bacardi Cocktail",
        doses=[Dose(Liquid.RUM, 1.5), Dose(Liquid.LIME_JUICE, 0.5)],
        addons=["0.75oz Grenadine"],
        method=Method.SHAKE,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        name="Bedford",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        addons=["Orange twist"],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Bellini",
        doses=[Dose(Liquid.PROSECCO, 3.5)],
        addons=[
            "Homemade peach purée (made by blending peach with ice & a bit of lemon juice)"
        ],
        method=Method.BUILD,
        preparation_recommendation="Add the purée in a flute, then the prosecco while stirring",
        custom_category=CustomCategory.WANT_TO_TRY,
        family=Family.SPARKLING_SOURS,
    ),
    Cocktail(
        name="Bensonhurst",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.MARASCHINO, 0.33),
            Dose(Liquid.AMARO, 0.5),
        ],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Betsy Ross",
        doses=[
            Dose(Liquid.BRANDY, 1.5),
            Dose(Liquid.PORTO, 1.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 2),
        ],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Bitter Stripper",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.GENTIANE, 0.5),
        ],
        addons=["Orange twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Black cat",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.BEER, 1.5),
            Dose(Liquid.GINGERBREAD_SYRUP, 0.5),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.ORPHANS,
    ),
    Cocktail(
        name="Black Feather",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, None),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        custom_category=CustomCategory.TRIED_NOT_FAVORITE,
        feedback="Try again with less dilution",
    ),
    Cocktail(
        name="Black Russian",
        doses=[Dose(Liquid.VODKA, 2), Dose(Liquid.KAHLUA, 1)],
        family=Family.DUOS_TRIOS,
        method=Method.STIR,
        custom_category=CustomCategory.CLASSIC,
    ),
    Cocktail(
        name="Blackthorn",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.ANGOSTURA_BITTERS, 3),
            Dose(Liquid.ABSINTHE, 1),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        custom_category=CustomCategory.FAVORITE,
    ),
    Cocktail(
        name="Blood and Sand",
        doses=[
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
            Dose(Liquid.CHERRY_BRANDY, 0.75),
        ],
        addons=["Orange juice to taste"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="Serve at brunch",
    ),
    Cocktail(
        name="Bloody Bull",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 2),
            Dose(Liquid.LEMON_JUICE, None),
        ],
        addons=[
            "2oz Beef bouillon",
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        method=Method.SHAKE,
        family=Family.SNAPPERS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Bloody Caesar",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 2),
            Dose(Liquid.LEMON_JUICE, None),
        ],
        addons=[
            "2oz clam juice",
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        family=Family.SNAPPERS,
        method=Method.SHAKE,
    ),
    Cocktail(
        name="Bloody Mary",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 4),
            Dose(Liquid.LEMON_JUICE, None),
        ],
        addons=[
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        family=Family.SNAPPERS,
        method=Method.SHAKE,
    ),
    Cocktail(
        name="Bobby Burns",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 1),
            Dose(Liquid.BENEDICTINE, 0.25),
        ],
        addons=["Lemon twist"],
        family=Family.FRENCH_ITALIAN,
        method=Method.STIR,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Bottom line",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.SHERRY, 1),
            Dose(Liquid.HONEY_LIQUEUR, 0.75),
            Dose(Liquid.AMARO, 0.25),
            Dose(Liquid.ORANGE_BITTERS, 1),
            Dose(Liquid.ANGOSTURA_BITTERS, 1),
        ],
        family=Family.FRENCH_ITALIAN,
        method=Method.STIR,
    ),
    Cocktail(
        name="Brandy Alexander",
        doses=[Dose(Liquid.BRANDY, 2), Dose(Liquid.CREME_DE_CACAO, 1)],
        addons=["1oz cream", "nutmeg"],
        family=Family.DUOS_TRIOS,
        method=Method.SHAKE,
    ),
    Cocktail(
        name="Brandy Crusta",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 2),
        ],
        addons=["lemon peel spiral"],
        family=Family.NEW_ORLEANS_SOURS,
        method=Method.SHAKE,
    ),
    Cocktail(
        name="Breakfast Martini",
        doses=[
            Dose(Liquid.GIN, 1.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        addons=["1.5 teaspoon orange marmalade", "Shredded orange peel"],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Bronx cocktail",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.25),
            Dose(Liquid.DRY_VERMOUTH, 0.25),
            Dose(Liquid.ORANGE_BITTERS, 1),
        ],
        addons=["1oz fresh orange juice"],
        method=Method.SHAKE,
        family=Family.ENHANCED_SOURS,
        feedback="Seems nice for brunch",
    ),
    Cocktail(
        name="Brooklyn Heights",
        doses=[
            Dose(Liquid.CAMPARI, 0.5),
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.AMARO, 0.25),
            Dose(Liquid.MARASCHINO, 0.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        preparation_recommendation="Rinse the glass with the Campari before pouring the rest",
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Butter Lemon Smoke",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.BRANDY, 1),
            Dose(Liquid.CHARTREUSE, 0.75),
            Dose(Liquid.BENEDICTINE, 0.75),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.ORPHANS,
        preparation_recommendation="Use very smoky Whisky",
    ),
    Cocktail(
        name="Cable Car",
        doses=[
            Dose(Liquid.RUM, 1.5),
            Dose(Liquid.GRAND_MARNIER, 0.75),
            Dose(Liquid.LEMON_JUICE, 1),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
        ],
        addons=["Cinnamon and sugar (rim glass with)", "Orange twist"],
        custom_category=CustomCategory.WANT_TO_TRY,
        preparation_recommendation="Use spiced Captain Morgan rum",
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        name="Café Brulôt",
        doses=[Dose(Liquid.TRIPLE_SEC, 1), Dose(Liquid.BRANDY, 1)],
        addons=[
            "1 lemon",
            "1 orange",
            "1 cinnamon stick",
            "4 whole cloves",
            "1.5 cup hot coffee",
        ],
        preparation_recommendation="Cf book, needs burning",
        method=Method.BUILD,
        family=Family.HOT_DRINKS,
    ),
    Cocktail(
        name="Caïpirinha",
        doses=[Dose(Liquid.CACHACA, 3), Dose(Liquid.LIME_JUICE, None)],
        addons=["1tbsp granulated sugar"],
        preparation_recommendation="Muddle the limes and sugar in glass, add ice and cachaça",
        method=Method.BUILD,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        name="Caïpiroska",
        doses=[Dose(Liquid.VODKA, 3), Dose(Liquid.LIME_JUICE, None)],
        preparation_recommendation="Muddle the limes and sugar in glass, add ice and vodka",
        method=Method.BUILD,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        name="Calvados cocktail",
        doses=[
            Dose(Liquid.CALVADOS, 1.5),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        addons=["1oz Fresh orange juice"],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        name="Caricature cocktail",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.CAMPARI, 0.5),
        ],
        addons=["0.5oz Grapefruit juice", "Orange twist"],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Casanova Cobbler",
        doses=[
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.SIMPLE_SYRUP, 0.25),
            Dose(Liquid.SWEET_VERMOUTH, 1.5),
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
        ],
        addons=["1 brandied cherry", "Orange wheel"],
        method=Method.BUILD,
        family=Family.ORPHANS,
    ),
    Cocktail(
        name="Champagne Cocktail",
        doses=[Dose(Liquid.CHAMPAGNE, 5.5), Dose(Liquid.ANGOSTURA_BITTERS, None)],
        addons=["Sugar cube soaked in Angostura", "Lemon twist"],
        method=Method.BUILD,
        family=Family.CHAMPAGNE_COCKTAILS,
    ),
    Cocktail(
        name="Chartreuse Swizzle",
        doses=[
            Dose(Liquid.CHARTREUSE, 1.5),
            Dose(Liquid.LIME_JUICE, 0.75),
        ],
        addons=["0.5oz Velvet Falernum", "1oz pineapple juice", "Ming sprig"],
        method=Method.BUILD,
        family=Family.ORPHANS,
    ),
    Cocktail(
        name="Clover club",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        addons=["0.5oz raspberry syrup (homemade cf book)", "0.25oz egg white"],
        method=Method.SHAKE,
        preparation_recommendation="DRY SHAKE to foam then shake with ice normally",
        family=Family.ENHANCED_SOURS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Compass box",
        doses=[
            Dose(Liquid.WHISKEY, 1),
            Dose(Liquid.BEER, 3),
            Dose(Liquid.ANGOSTURA_BITTERS, 3),
        ],
        addons=["1 maraschino cherry"],
        preparation_recommendation="Use stout for beer",
        method=Method.STIR,
        family=Family.ORPHANS,
    ),
    Cocktail(
        name="Corpse reviver N°1",
        doses=[
            Dose(
                Liquid.BRANDY,
                1.5,
            ),
            Dose(Liquid.CALVADOS, 0.75),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
        ],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="Corpse reviver N°2",
        doses=[
            Dose(Liquid.GIN, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.LILLET_BLONDE, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
            Dose(Liquid.ABSINTHE, 0.25),
        ],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        name="Cosmopolitan",
        doses=[
            Dose(Liquid.VODKA, 1.5),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.LIME_JUICE, 0.5),
        ],
        addons=["1oz cranberry juice"],
        feedback="Seems good for mom or people who like sweeter cocktails",
        custom_category=CustomCategory.WANT_TO_TRY,
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        name="Cuzco cocktail",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.APEROL, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.SIMPLE_SYRUP, 0.75),
        ],
        addons=["0.5oz grapefruit juice", "rince with 0.5oz kirschwasser (?)"],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
    ),
    Cocktail(
        name="Daiquiri",
        doses=[
            Dose(Liquid.RUM, 2),
            Dose(Liquid.LIME_JUICE, 1),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
        ],
        method=Method.SHAKE,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        name="Dark and stormy",
        doses=[Dose(Liquid.RUM, 2), Dose(Liquid.GINGER_BEER, 3)],
        addons=["Lime wedge"],
        method=Method.BUILD,
        family=Family.HIGHBALLS,
    ),
    Cocktail(
        name="Dirty martini",
        doses=[Dose(Liquid.GIN, 2.5), Dose(Liquid.DRY_VERMOUTH, 1.5)],
        addons=["Olive brine to taste", "1 olive"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Dog's nose",
        doses=[Dose(Liquid.BEER, 12), Dose(Liquid.GIN, 2)],
        addons=["2tsp brown sugar", "Nutmeg"],
        family=Family.ORPHANS,
        method=Method.BUILD,
        preparation_recommendation="Use porter or stout, heat it in the microwave then add the rest and stir",
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="The Dubliner",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        addons=["Maraschino cherry"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Dreamy Dorini smoking martini",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.WHISKEY, 0.5),
            Dose(Liquid.PASTIS, None),
        ],
        addons=["lemon twist"],
        preparation_recommendation="Use smoky scotch",
        custom_category=CustomCategory.WANT_TO_TRY,
        family=Family.ORPHANS,
        method=Method.STIR,
    ),
    Cocktail(
        name="Earl grey marteani",
        doses=[
            Dose(Liquid.GIN, 1.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
            Dose(Liquid.SIMPLE_SYRUP, 1),
        ],
        addons=["1 egg white", "lemon twist"],
        preparation_recommendation="Infuse the gin first, by letting it sit in a bowl with earl grey tea for 2h",
        custom_category=CustomCategory.WANT_TO_TRY,
        family=Family.SIMPLE_SOURS,
        method=Method.SHAKE,
    ),
    Cocktail(
        name="El Presidente",
        doses=[
            Dose(Liquid.RUM, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 1.5),
            Dose(Liquid.GRAND_MARNIER, 1),
        ],
        addons=["orange twist", "0.5tsp grenadine"],
        preparation_recommendation="Use white rum, and dolin blanc vermouth",
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        name="Final Ward",
        doses=[
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.MARASCHINO, 0.75),
            Dose(Liquid.CHARTREUSE, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
        ],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
    ),
    Cocktail(
        name="Fish house punch",
        doses=[
            Dose(Liquid.RUM, None),
            Dose(Liquid.BRANDY, 13),
            Dose(Liquid.SIMPLE_SYRUP, 4),
            Dose(Liquid.LEMON_JUICE, 5),
            Dose(Liquid.LIME_JUICE, 5),
        ],
        preparation_recommendation="Use a full bottle of dark rum, and part of the brandy should be peach brandy."
        "Stir in a large bowl, refrigerate 4h, serve with ice",
        method=Method.STIR,
        family=Family.PUNCHES,
    ),
    Cocktail(
        name="Fog cutter",
        doses=[
            Dose(Liquid.RUM, 2),
            Dose(Liquid.BRANDY, 1),
            Dose(Liquid.GIN, 0.5),
            Dose(Liquid.LEMON_JUICE, 2),
            Dose(Liquid.SHERRY, 0.5),
        ],
        addons=["0.5oz orgeat syrup"],
        method=Method.SHAKE,
        preparation_recommendation="Float the sherry at the end",
        family=Family.TIKI,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
    Cocktail(
        name="French 75",
        doses=[
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GIN, 2),
            Dose(Liquid.CHAMPAGNE, 4),
        ],
        method=Method.BUILD,
        family=Family.SPARKLING_SOURS,
        custom_category=CustomCategory.WANT_TO_TRY,
    ),
]

# Not transcribed
# "Aviation: World class style" (variation on Aviation)
# "Banana Daiquiri Jelly Shot" (Jelly)
# "Blue Blazer (pyrotechnic)
# "Blue devil" (uses super specific Hypnotiq liqueur)
# "Dubonnet cocktail" (uses specific Dubonnet Rouge)
# "Dutch Coupe" (uses Jenever, Cynar, orange flower water)
# "Flame of love"
# "Floss 75"
