from sqlalchemy.exc import IntegrityError

from db.db_connector import DbConnector
from domain.entitites import (Cocktail, Dose, Family, FavoriteStatus, Liquid,
                              Method)

cocktails_seed = [
    Cocktail(
        cocktail_id=0,
        name="Alaska",
        doses=[Dose(Liquid.GIN, 1.5), Dose(Liquid.CHARTREUSE, 0.5)],
        method=Method.STIR,
        family=Family.DUOS_TRIOS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Alexander",
        doses=[Dose(Liquid.GIN, 2), Dose(Liquid.CREME_DE_CACAO, 1)],
        addons=["1 ounce cream"],
        method=Method.SHAKE,
        family=Family.DUOS_TRIOS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Amaro Crusta",
        doses=[
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.LIME_JUICE, 0.5),
            Dose(Liquid.AMARO, 2),
        ],
        addons=[
            "1 spoon orange marmalade",
            "Orange twist",
            "Vanilla sugar to rim glass",
        ],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="I simplified a lot. Actual recipe with a mix of Amaros "
        "(Montenegro, Picon, Rabarbaro)."
        "Dry shake marmalade and citrus juice, then add ice and shake the rest",
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Americano",
        doses=[Dose(Liquid.CAMPARI, 1.5), Dose(Liquid.SWEET_VERMOUTH, 1.5)],
        addons=["2oz club Soda", "Orange twist"],
        method=Method.BUILD,
        family=Family.HIGHBALLS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Am I Blue",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.MARASCHINO, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 1),
            Dose(Liquid.CHAMPAGNE, 0),
        ],
        addons=["Flamed orange twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        favorite_status=FavoriteStatus.BOOKMARKED,
        preparation_recommendation="Use Blue Label Johnny Walker Scotch",
    ),
    Cocktail(
        cocktail_id=0,
        name="Angel's Share",
        doses=[
            Dose(Liquid.CHARTREUSE, 1),
            Dose(Liquid.BRANDY, 1.25),
            Dose(Liquid.WALNUT_LIQUEUR, 1.25),
            Dose(Liquid.PORTO, 0.5),
        ],
        method=Method.STIR,
        family=Family.ORPHANS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Aperol Spritz",
        doses=[Dose(Liquid.APEROL, 2), Dose(Liquid.PROSECCO, 3)],
        addons=["1 Splash Club soda", "Orange Wheel"],
        method=Method.BUILD,
        family=Family.ORPHANS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Atom Limo",
        doses=[
            Dose(Liquid.WHISKEY, 1),
            Dose(Liquid.SHERRY, 1),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GINGER_ALE, 0),
            Dose(Liquid.APPLE_JUICE, 1),
        ],
        addons=[
            "Fresh Ginger",
            "1 mint sprig",
            "1 apple slice",
            "1 cherry",
        ],
        method=Method.BUILD,
        family=Family.ORPHANS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Autumn Winds",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.BENEDICTINE, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 1),
        ],
        addons=["0.5oz homemade butter sage liqueur (cf book)", "1 sage leaf"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Aviation Cocktail",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.CREME_DE_VIOLETTE, 0.5),
            Dose(Liquid.MARASCHINO, 0.25),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Aztec's Mark",
        doses=[
            Dose(Liquid.WHISKEY, 1.25),
            Dose(Liquid.BENEDICTINE, 0.25),
            Dose(Liquid.CREME_DE_CACAO, 0.5),
        ],
        addons=["2 drops Tabasco", "Orange twist"],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="Use Maker's Mark Bourbon",
    ),
    Cocktail(
        cocktail_id=0,
        name="Bacardi Cocktail",
        doses=[Dose(Liquid.RUM_LIGHT, 1.5), Dose(Liquid.LIME_JUICE, 0.5)],
        addons=["0.75oz Grenadine"],
        method=Method.SHAKE,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bedford",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        addons=["Orange twist"],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bellini",
        doses=[Dose(Liquid.PROSECCO, 3.5)],
        addons=[
            "Homemade peach purée (made by blending peach with ice & a bit of lemon juice)"
        ],
        method=Method.BUILD,
        preparation_recommendation="Add the purée in a flute, then the prosecco while stirring",
        favorite_status=FavoriteStatus.BOOKMARKED,
        family=Family.SPARKLING_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bensonhurst",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.MARASCHINO, 0.33),
            Dose(Liquid.AMARO, 0.5),
        ],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Betsy Ross",
        doses=[
            Dose(Liquid.BRANDY, 1.5),
            Dose(Liquid.PORTO, 1.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 2),
        ],
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bitter Stripper",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.GENTIANE, 0.5),
        ],
        addons=["Orange twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Black cat",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.BEER, 1.5),
            Dose(Liquid.GINGERBREAD_SYRUP, 0.5),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.ORPHANS,
        preparation_recommendation="Use Guinness for the beer. Don't put too much syrup",
    ),
    Cocktail(
        cocktail_id=0,
        name="Black Feather",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 0),
        ],
        addons=["Orange twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        feedback="Try again with less dilution",
    ),
    Cocktail(
        cocktail_id=0,
        name="Black Russian",
        doses=[Dose(Liquid.VODKA, 2), Dose(Liquid.KAHLUA, 1)],
        family=Family.DUOS_TRIOS,
        method=Method.STIR,
    ),
    Cocktail(
        cocktail_id=0,
        name="Blackthorn",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.ANGOSTURA_BITTERS, 3),
            Dose(Liquid.ABSINTHE, 0),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        favorite_status=FavoriteStatus.FAVORITE,
        preparation_recommendation="Use one or two dashes of absinthe",
    ),
    Cocktail(
        cocktail_id=0,
        name="Blood and Sand",
        doses=[
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
            Dose(Liquid.CHERRY_BRANDY, 0.75),
            Dose(Liquid.ORANGE_JUICE, 0),
        ],
        method=Method.SHAKE,
        family=Family.ORPHANS,
        preparation_recommendation="Serve at brunch",
    ),
    Cocktail(
        cocktail_id=0,
        name="Bloody Bull",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 2),
            Dose(Liquid.LEMON_JUICE, 0),
        ],
        addons=[
            "2oz Beef bouillon",
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        method=Method.SHAKE,
        family=Family.SNAPPERS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bloody Caesar",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 2),
            Dose(Liquid.LEMON_JUICE, 0),
        ],
        addons=[
            "2oz clam juice",
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        family=Family.SNAPPERS,
        method=Method.SHAKE,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bloody Mary",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.TOMATO_JUICE, 4),
            Dose(Liquid.LEMON_JUICE, 0),
        ],
        addons=[
            "Salt",
            "Pepper",
            "Horseradish",
            "Worcestershire sauce",
            "Hot sauce",
            "Lemon wedge",
            "Celery",
        ],
        family=Family.SNAPPERS,
        method=Method.SHAKE,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bobby Burns",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 1),
            Dose(Liquid.ABSINTHE, 0.25),
        ],
        addons=["Lemon twist"],
        family=Family.FRENCH_ITALIAN,
        method=Method.STIR,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bottom line",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.SHERRY, 1),
            Dose(Liquid.HONEY_LIQUEUR, 0.75),
            Dose(Liquid.AMARO, 0.25),
            Dose(Liquid.ORANGE_BITTERS, 1),
            Dose(Liquid.ANGOSTURA_BITTERS, 1),
        ],
        family=Family.FRENCH_ITALIAN,
        method=Method.STIR,
    ),
    Cocktail(
        cocktail_id=0,
        name="Brandy Alexander",
        doses=[Dose(Liquid.BRANDY, 2), Dose(Liquid.CREME_DE_CACAO, 1)],
        addons=["1oz cream", "nutmeg"],
        family=Family.DUOS_TRIOS,
        method=Method.SHAKE,
    ),
    Cocktail(
        cocktail_id=0,
        name="Brandy Crusta",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ANGOSTURA_BITTERS, 2),
        ],
        addons=["Lemon peel spiral"],
        family=Family.NEW_ORLEANS_SOURS,
        method=Method.SHAKE,
    ),
    Cocktail(
        cocktail_id=0,
        name="Breakfast Martini",
        doses=[
            Dose(Liquid.GIN, 1.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        addons=["1.5 teaspoon orange marmalade", "Shredded orange peel"],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Bronx cocktail",
        doses=[
            Dose(Liquid.GIN, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.25),
            Dose(Liquid.DRY_VERMOUTH, 0.25),
            Dose(Liquid.ORANGE_BITTERS, 1),
            Dose(Liquid.ORANGE_JUICE, 1),
        ],
        addons=["Orange twist"],
        method=Method.SHAKE,
        family=Family.ENHANCED_SOURS,
        feedback="Seems nice for brunch",
    ),
    Cocktail(
        cocktail_id=0,
        name="Brooklyn Heights",
        doses=[
            Dose(Liquid.CAMPARI, 0.5),
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.AMARO, 0.25),
            Dose(Liquid.MARASCHINO, 0.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        preparation_recommendation="Rinse the glass with the Campari before pouring the rest",
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Butter Lemon Smoke",
        doses=[
            Dose(Liquid.WHISKEY, 1.5),
            Dose(Liquid.BRANDY, 1),
            Dose(Liquid.CHARTREUSE, 0.75),
            Dose(Liquid.BENEDICTINE, 0.75),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.ORPHANS,
        preparation_recommendation="Use very smoky Whisky",
    ),
    Cocktail(
        cocktail_id=0,
        name="Cable Car",
        doses=[
            Dose(Liquid.RUM_DARK, 1.5),
            Dose(Liquid.GRAND_MARNIER, 0.75),
            Dose(Liquid.LEMON_JUICE, 1),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
        ],
        addons=["Cinnamon and sugar (rim glass with)", "Orange twist"],
        favorite_status=FavoriteStatus.BOOKMARKED,
        preparation_recommendation="Use spiced Captain Morgan rum",
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Café Brulôt",
        doses=[Dose(Liquid.TRIPLE_SEC, 1), Dose(Liquid.BRANDY, 1)],
        addons=[
            "1 lemon",
            "1 orange",
            "1 cinnamon stick",
            "4 whole cloves",
            "1.5 cup hot coffee",
        ],
        preparation_recommendation="Cf book, needs burning",
        method=Method.BUILD,
        family=Family.HOT_DRINKS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Caïpirinha",
        doses=[Dose(Liquid.CACHACA, 3), Dose(Liquid.LIME_JUICE, 0)],
        addons=["1tbsp granulated sugar"],
        preparation_recommendation="Muddle 4-6 lime wedges and the sugar in glass, add ice and cachaça",
        method=Method.BUILD,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Caïpiroska",
        doses=[Dose(Liquid.VODKA, 3), Dose(Liquid.LIME_JUICE, 0)],
        preparation_recommendation="Muddle 4-6 lime wedges and the sugar in glass, add ice and vodka",
        method=Method.BUILD,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Calvados cocktail",
        doses=[
            Dose(Liquid.CALVADOS, 1.5),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.ORANGE_BITTERS, 2),
            Dose(Liquid.ORANGE_JUICE, 1),
        ],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Caricature cocktail",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.CAMPARI, 0.5),
            Dose(Liquid.GRAPEFRUIT_JUICE, 0.5),
        ],
        addons=["Orange twist"],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Casanova Cobbler",
        doses=[
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.SIMPLE_SYRUP, 0.25),
            Dose(Liquid.SWEET_VERMOUTH, 1.5),
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.5),
        ],
        addons=["1 brandied cherry", "Orange wheel"],
        method=Method.BUILD,
        family=Family.ORPHANS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Champagne Cocktail",
        doses=[Dose(Liquid.CHAMPAGNE, 5.5), Dose(Liquid.ANGOSTURA_BITTERS, 0)],
        addons=["Sugar cube soaked in Angostura", "Lemon twist"],
        method=Method.BUILD,
        family=Family.CHAMPAGNE_COCKTAILS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Chartreuse Swizzle",
        doses=[
            Dose(Liquid.CHARTREUSE, 1.5),
            Dose(Liquid.LIME_JUICE, 0.75),
            Dose(Liquid.PINEAPPLE_JUICE, 1),
        ],
        addons=["0.5oz Velvet Falernum", "Mint sprig"],
        method=Method.BUILD,
        family=Family.ORPHANS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Clover club",
        doses=[
            Dose(Liquid.GIN, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.5),
        ],
        addons=["0.5oz raspberry syrup (homemade cf book)", "0.25oz egg white"],
        method=Method.SHAKE,
        preparation_recommendation="DRY SHAKE to foam then shake with ice normally",
        family=Family.ENHANCED_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Compass box",
        doses=[
            Dose(Liquid.WHISKEY, 1),
            Dose(Liquid.BEER, 3),
            Dose(Liquid.ANGOSTURA_BITTERS, 3),
        ],
        addons=["1 maraschino cherry"],
        preparation_recommendation="Use stout for beer",
        method=Method.STIR,
        family=Family.ORPHANS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Corpse reviver N°1",
        doses=[
            Dose(
                Liquid.BRANDY,
                1.5,
            ),
            Dose(Liquid.CALVADOS, 0.75),
            Dose(Liquid.SWEET_VERMOUTH, 0.75),
        ],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Corpse reviver N°2",
        doses=[
            Dose(Liquid.GIN, 0.75),
            Dose(Liquid.TRIPLE_SEC, 0.75),
            Dose(Liquid.LILLET_BLONDE, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
            Dose(Liquid.ABSINTHE, 0.25),
        ],
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Cosmopolitan",
        doses=[
            Dose(Liquid.VODKA, 1.5),
            Dose(Liquid.TRIPLE_SEC, 0.5),
            Dose(Liquid.LIME_JUICE, 0.5),
            Dose(Liquid.CRANBERRY_JUICE, 1),
        ],
        addons=["Flamed orange twist"],
        preparation_recommendation="Use citrus vodka",
        feedback="Seems good for mom or people who like sweeter cocktails",
        favorite_status=FavoriteStatus.BOOKMARKED,
        method=Method.SHAKE,
        family=Family.NEW_ORLEANS_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Cuzco cocktail",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.APEROL, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.SIMPLE_SYRUP, 0.75),
            Dose(Liquid.GRAPEFRUIT_JUICE, 0.5),
        ],
        addons=["rince with 0.5oz kirschwasser (?)", "grapefruit twist"],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Daiquiri",
        doses=[
            Dose(Liquid.RUM_LIGHT, 2),
            Dose(Liquid.LIME_JUICE, 1),
            Dose(Liquid.SIMPLE_SYRUP, 0.5),
        ],
        addons=["Lime wedge"],
        method=Method.SHAKE,
        family=Family.SIMPLE_SOURS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Dark and stormy",
        doses=[Dose(Liquid.RUM_DARK, 2), Dose(Liquid.GINGER_BEER, 3)],
        addons=["Lime wedge"],
        method=Method.BUILD,
        family=Family.HIGHBALLS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Dirty martini",
        doses=[Dose(Liquid.GIN, 2.5), Dose(Liquid.DRY_VERMOUTH, 1.5)],
        addons=["Olive brine to taste", "1 olive"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Dog's nose",
        doses=[Dose(Liquid.BEER, 12), Dose(Liquid.GIN, 2)],
        addons=["2tsp brown sugar", "Nutmeg"],
        family=Family.ORPHANS,
        method=Method.BUILD,
        preparation_recommendation="Use porter or stout, heat it in the microwave then add the rest and stir",
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="The Dubliner",
        doses=[
            Dose(Liquid.WHISKEY, 2),
            Dose(Liquid.SWEET_VERMOUTH, 0.5),
            Dose(Liquid.GRAND_MARNIER, 0.5),
            Dose(Liquid.ORANGE_BITTERS, 2),
        ],
        addons=["Maraschino cherry"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Dreamy Dorini smoking martini",
        doses=[
            Dose(Liquid.VODKA, 2),
            Dose(Liquid.WHISKEY, 0.5),
            Dose(Liquid.PASTIS, 0),
        ],
        addons=["lemon twist"],
        preparation_recommendation="Use smoky scotch + 2/3 drops pastis",
        favorite_status=FavoriteStatus.BOOKMARKED,
        family=Family.ORPHANS,
        method=Method.STIR,
    ),
    Cocktail(
        cocktail_id=0,
        name="Earl grey marteani",
        doses=[
            Dose(Liquid.GIN, 1.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
            Dose(Liquid.SIMPLE_SYRUP, 1),
        ],
        addons=["1 egg white", "lemon twist"],
        preparation_recommendation="Infuse the gin first, by letting it sit in a bowl with earl grey tea for 2h",
        favorite_status=FavoriteStatus.BOOKMARKED,
        family=Family.SIMPLE_SOURS,
        method=Method.SHAKE,
    ),
    Cocktail(
        cocktail_id=0,
        name="El Presidente",
        doses=[
            Dose(Liquid.RUM_LIGHT, 1.5),
            Dose(Liquid.DRY_VERMOUTH, 1.5),
            Dose(Liquid.GRAND_MARNIER, 1),
        ],
        addons=["Orange twist", "0.5tsp grenadine"],
        preparation_recommendation="Use white rum, and dolin blanc vermouth",
        method=Method.SHAKE,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Final Ward",
        doses=[
            Dose(Liquid.WHISKEY, 0.75),
            Dose(Liquid.MARASCHINO, 0.75),
            Dose(Liquid.CHARTREUSE, 0.75),
            Dose(Liquid.LEMON_JUICE, 0.75),
        ],
        method=Method.SHAKE,
        family=Family.INTERNATIONAL_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Fish house punch",
        doses=[
            Dose(Liquid.RUM_DARK, 0),
            Dose(Liquid.BRANDY, 13),
            Dose(Liquid.SIMPLE_SYRUP, 4),
            Dose(Liquid.LEMON_JUICE, 5),
            Dose(Liquid.LIME_JUICE, 5),
        ],
        preparation_recommendation="Use a full bottle of dark rum, and part of the brandy should be peach brandy."
        "Stir in a large bowl, refrigerate 4h, serve with ice",
        method=Method.STIR,
        family=Family.PUNCHES,
    ),
    Cocktail(
        cocktail_id=0,
        name="Fog cutter",
        doses=[
            Dose(Liquid.RUM_LIGHT, 2),
            Dose(Liquid.BRANDY, 1),
            Dose(Liquid.GIN, 0.5),
            Dose(Liquid.LEMON_JUICE, 2),
            Dose(Liquid.SHERRY, 0.5),
        ],
        addons=["0.5oz orgeat syrup"],
        method=Method.SHAKE,
        preparation_recommendation="Float the sherry at the end",
        family=Family.TIKI,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="French 75",
        doses=[
            Dose(Liquid.SIMPLE_SYRUP, 0.25),
            Dose(Liquid.LEMON_JUICE, 0.5),
            Dose(Liquid.GIN, 2),
            Dose(Liquid.CHAMPAGNE, 4),
        ],
        method=Method.BUILD,
        family=Family.SPARKLING_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Frozen Piña Colada",
        doses=[
            Dose(Liquid.RUM_DARK, 2),
            Dose(Liquid.PINEAPPLE_JUICE, 2),
            Dose(Liquid.COCONUT_CREAM, 1.5),
        ],
        addons=["1 maraschino cherry", "1 pineapple cube"],
        method=Method.BLEND,
        preparation_recommendation="Blend with ice, then add the garnish",
        family=Family.FROZEN_DRINKS,
    ),
    Cocktail(
        cocktail_id=0,
        name="Gibson",
        doses=[Dose(Liquid.GIN, 2.5), Dose(Liquid.DRY_VERMOUTH, 0.5)],
        preparation_recommendation="Alternatively use vodka",
        addons=["1-3 cocktail onions"],
        method=Method.STIR,
        family=Family.FRENCH_ITALIAN,
    ),
    Cocktail(
        cocktail_id=0,
        name="Gimlet",
        doses=[Dose(Liquid.GIN, 2.5), Dose(Liquid.LIME_JUICE, 0.75)],
        addons=["Lime wedge"],
        preparation_recommendation="Actual recipe uses lime juice cordial",
        family=Family.DUOS_TRIOS,
        method=Method.STIR,
    ),
    Cocktail(
        cocktail_id=0,
        name="Gin gin mule",
        doses=[
            Dose(Liquid.LIME_JUICE, 0.75),
            Dose(Liquid.SIMPLE_SYRUP, 1),
            Dose(Liquid.GIN, 1.75),
            Dose(Liquid.GINGER_BEER, 1),
        ],
        addons=["2 mint sprigs", "Lime wheel"],
        method=Method.SHAKE,
        preparation_recommendation="Muddle juice + syrup with a mint sprig, then add the rest and shake. "
        "Second mint sprig for garnish.",
        family=Family.SPARKLING_SOURS,
        favorite_status=FavoriteStatus.BOOKMARKED,
    ),
    Cocktail(
        cocktail_id=0,
        name="Gotham cocktail",
        doses=[
            Dose(Liquid.BRANDY, 2),
            Dose(Liquid.DRY_VERMOUTH, 1),
            Dose(Liquid.CREME_DE_CASSIS, 0.5),
            Dose(Liquid.LEMON_JUICE, 0.25),
        ],
        addons=["Lemon twist"],
        method=Method.STIR,
        family=Family.INTERNATIONAL_SOURS,
    ),
    Cocktail(cocktail_id=0, name="Grasshoper", doses=[]),
]

# Not transcribed
# "Aviation: World class style" (variation on Aviation)
# "Banana Daiquiri Jelly Shot" (Jelly)
# "Blue Blazer (pyrotechnic)
# "Blue devil" (uses super specific Hypnotiq liqueur)
# "Dubonnet cocktail" (uses specific Dubonnet Rouge)
# "Dutch Coupe" (uses Jenever, Cynar, orange flower water)
# "Flame of love"
# "Floss 75"
# "Almost blow my skull off": looks bad
# "Godfather, godmother: too simple

if __name__ == "__main__":
    db_connector = DbConnector()

    for cocktail in cocktails_seed:
        try:
            new_id = db_connector.create_cocktail(cocktail)
        except IntegrityError as e:
            if (
                'duplicate key value violates unique constraint "cocktails_name_key'
                in str(e.orig)
            ):
                print(f"Cocktail {cocktail.name} already exists")
                continue
            raise
        if cocktail.favorite_status != FavoriteStatus.NONE:
            db_connector.set_cocktail_favorite_status(new_id, cocktail.favorite_status)
        if cocktail.feedback:
            db_connector.set_cocktail_feedback(new_id, cocktail.feedback)
        print(f"Cocktail {cocktail.name} created")
